### ISSUE TITLE
on this day in history

### ISSUE THREAD

**Issue by maaarghk** [maaarghk/SteamieBot#10]

**Comment by incompetentfox** [comment]
I think I've got something for this. Will test and commit if it works.

**Comment by incompetentfox** [comment]
Having some difficulty testing (I don't have the right API key for the weather) but I'm fairly confident I haven't broken anything. Famous last words, right? Anyway, I've been careful to make sure that if there's any problem it gets caught at function level rather than making the whole bot fall over like a fresher on a Sauchiehall Street pub crawl. By all means, test it or PM me a copy of the details I'd need to test it myself, but it shouldn't break anything!

**Comment by maaarghk** [comment]
@timlardner should be able to sort you out with working ini files, or you could generate your own api key for the weather and keep it for your own purposes!

**Comment by timlardner** [comment]
I can share the private .ini fiiles via Dropbox?

**Comment by incompetentfox** [comment]
That'd be great, thanks! You could PM me the link on Reddit?

**Comment by timlardner** [comment]
PM'd the link to /r/steamiebottest so that @maaarghk can see it too.
